# Generated by Django 5.0.6 on 2024-07-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
